version: "3.8"
services:
    web:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf     
    db: 
        image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: root
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
    app:
        build: 
            dockerfile: ./php/Dockerfile
        volumes:
          - ./app:/app